name: tautulli-snap # you probably want to 'snapcraft register <name>'
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Python based monitoring and tracking tool for Plex Media Server. # 79 char long summary
description: |
  A python based web application for monitoring, analytics and notifications for Plex Media Server.
  This project is based on code from Headphones and PlexWatchWeb.

confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

parts:
  tautulli:
    plugin: dump
    source: https://github.com/Tautulli/Tautulli.git
    stage-packages: [python, python-setuptools]

apps:
  tautulli:
    command: Tautulli.py --datadir $SNAP_COMMON/Tautulli
    daemon: simple
    plugs: [network, network-bind]